FROM pennsieve/openjdk:8-alpine3.9

# Install bash for entrypoint script
USER root
RUN apk add --no-cache bash
USER pennsieve

# Copy the assembly JAR
# ARG JAR_FILE=discover-publish/target/scala-2.13/multipart-uploader-assembly-bootstrap-*.jar
COPY --chown=pennsieve:pennsieve csv-s3-ops.jar /app/csv-s3-ops.jar

# Set working directory
WORKDIR /app

# Default to CSV S3 Copy main class
ENV MAIN_CLASS=com.pennsieve.publish.CsvS3OpsMain

# Java options for container environment
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"

# Run the application with the specified main class
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -cp  /app/csv-s3-ops.jar $MAIN_CLASS"]
